### ISSUE TITLE
onbeforeunload no longer shows custom messages

### ISSUE THREAD

**Issue by timdorr** [mjackson/history#299]
Chrome 51 should be going to stable next week. It [removes custom messages for onbeforeunload dialogs](https://www.chromestatus.com/feature/5349061406228480). Firefox [hasn't shown them for years](https://bugzilla.mozilla.org/show_bug.cgi?id=588292). Safari [removed them in 9.1](https://developer.apple.com/library/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html). Opera will get it in their next release once it makes its way downstream from WebKit.

Given that it's dead in the water, we can likely clean up [some of the code](https://github.com/mjackson/history/blob/master/modules/useBeforeUnload.js) that deals with messages and drop support for them. It's always good to see a lot of red in a PR 😄

**Comment by mjackson** [comment]
Seems like this is just an update to [our docs](https://github.com/ReactTraining/history/blob/master/docs/ConfirmingNavigation.md), right? And maybe a comment in the code? Something like "hey, returning a string message here isn't gonna work in modern browsers".

I initially split up `listenBefore` and `listenBeforeUnload` because they behaved so differently I thought they deserved to be separate methods. This is just one more way they differ.

**Comment by mjackson** [comment]
v4 no longer includes support for `onbeforeunload`, so we can close this. It's out of scope for us.
