### ISSUE TITLE
handle possible 'URI malformed' error of decodeURIComponent method

### ISSUE THREAD

**Issue by pd4d10** [mjackson/history#312]
Hi, all

When I use `react-router`(depends on `history`) to build server side rendering webapp, request with query string such as `?param=%A8` always makes annoying 500 error, because `%A8` is not a correct encoded query string:

```
> decodeURIComponent('param=%A8')
Uncaught URIError: URI malformed(…)
```

I've made a PR to `query-string` to handle this error, see:
https://github.com/sindresorhus/query-string/pull/65

@sindresorhus thinks this maybe not a correct way.

Should we handle this error on `history`?

**Comment by taion** [comment]
We should probably handle it here. Not sure how. The signature on `listen` doesn't allow an error.

**Comment by Tin** [comment]
Let's brainstorm this issue:

It happens on malformed query string value. That means there's no right/wrong behavior, it's just adding a robust default behavior.

In a react-router application, code may looks like:

```
import {browserHistory} from 'react-router';
const store = createReduxStore(browserHistory);
```

And then a malformed URI may looks like `https://site.com/search?query=a%b`. It's invalid, because `%` should be encoded as `a%25b`. But this kind of error may happens when user try to modify the url, or when they made mistake copy and paste the url.

In this scenario, the above code will be fail unexpectedly. User won't see anything, the application will fail on initialization. That's pretty bad user/developer experience.

We can argue maybe it's developer's responsibility to handle this, so history should surface this error. But the interface may be ugly, and the benefit is very low. The `useQueries` interface allow passing different `parseQueryString` implementation, that's a good design to fix this issue. But then the react-router's initialization code become clunky:

```
import {useRouterHistory} from 'react-router';
import createBrowserHistory from 'react-router/node_modules/history/lib/createBrowserHistory';

const browserHistory = useRouterHistory(createBrowserHistory)({
  parseQueryString: function () {
    try {
      return queryString.parse.apply(null, arguments);
    } catch (e) {
      return qs.parse.apply(null, arguments);
    }
  }
});

**Comment by taion** [comment]
Possibly the only correct behavior here is to set `query` to `null` in this case. If the user desires actual error semantics, he or she can use a query parser that catches and handles any relevant errors.

**Comment by mjackson** [comment]
We no longer have anything to do with parsing query strings. v4 puts that problem squarely in user space. I'd welcome a PR to fix it in whatever version you guys are using.

**Comment by ChrisCinelli** [comment]
I thought you guys you would have kept supporting v2...
