### ISSUE TITLE
Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///C:/404' cannot be created in a document with origin 'null' and URL 'file:///C:/Users/User/Desktop/recipe%20app/build/index.html'.

### ISSUE THREAD

**Issue by dagman** [mjackson/history#366]
I have run `npm run build` to get production version of my Recipe app.
And when i had open `index.html`  i get the abovementioned error in console.
I am not using jquery in my app.
I am building app using React, Redux and React-Router.
The error pointing to `createBrowserHistory.js` file line 119.
Thanks for help in advance.
![history error 2](https://cloud.githubusercontent.com/assets/13398931/18482893/a3693be8-79ea-11e6-8cb4-0009f2f266a8.png)
![history error](https://cloud.githubusercontent.com/assets/13398931/18482894/a36ecf7c-79ea-11e6-8e0b-35460648db3b.png)

**Comment by mjackson** [comment]
I'm sorry, but I can't help you without more information.

**Comment by dcporter44** [comment]
Having same problem. Did you figure out a solution?

**Comment by shankargounder** [comment]
Having same problem. any solution?

**Comment by raveclassic** [comment]
The problem is obviously in serving from 'file://' - that's why "history state object cannot be created in a document with origin 'null'". And origin is 'null' when serving from 'file'.
None of histories work: neither `createHashHistory`, nor `createBrowserHistory`, not even `createMemoryHistory`.

@mjackson Please reopen, the problem is still here.

**Comment by dvakatsiienko** [comment]
Yes, the problem is stil here
