### ISSUE TITLE
Memory history go() is synchronous

### ISSUE THREAD

**Issue by jankuca** [mjackson/history#414]
`go()` is performed asynchronously when using browser history whilst the memory history implementation emits `popstate` events synchronously.

Is this the desired behavior?

**Comment by mjackson** [comment]
Memory history doesn't actually "emit popstate events". It just calls your listeners. It doesn't even use the browser's `popstate` event because it doesn't depend on being in a browser.

As far as whether or not listeners are fired synchronously when you call `go`, this is not defined. In browsers we have to wait for the `popstate` event, but we don't have that restriction when we're managing the history stack ourselves.

**Comment by jankuca** [comment]
I realize this is the situation. What I'm asking is whether it is a good idea to have this difference in behavior for the two implementations.

I'm in a position where I need to use both memory and browser history implementations (electron vs browser) and wrap all `go()` calls in `setImmediate()` to achieve consistent async behavior.

**Comment by mjackson** [comment]
You should be able to write your app code in a way that doesn't care whether the API is async or not since the behavior is not defined. At some point in the future browsers might start emitting `popstate` events synchronously. Who knows? What I'm saying is you shouldn't care in the code you write.
